version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: university-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: university-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/university_db
      SPRING_DATASOURCE_USERNAME: university_user
      SPRING_DATASOURCE_PASSWORD: university_pass

  frontend:
    build: ./frontend
    container_name: university-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  mysql_data:
